channels:
  - conda-forge
dependencies:
  - dask=2024.12.1
  - flox=0.9.15
  - h5netcdf
  - numba=0.60.0
  - numbagg=0.8.2
  - pandas=2.2.3
  - pyarrow=19.0.0
  - python=3.12.8
  - rasterio=1.4.3
  - rioxarray=0.18.2
  - snowmaus
  - tornado=6.4.2
  - xarray=2025.1.1
  - zarr=3.0.1
